language: python
python:
  - "3.7"
  - "3.6"
  - "3.8"
<<<<<<< HEAD
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
after_success:
  - codecov
env:
  CODECOV_TOKEN="679b9741-44f0-408e-a48b-c17a1b698670"
